name: spras
channels:
  - conda-forge
dependencies:
  - adjusttext=0.7.3.1
  - bioconda::snakemake-minimal=7.19.1
  - docker-py=5.0
  - matplotlib=3.5
  - networkx=2.8
  - pandas=1.4
  - pre-commit=2.20 # Only required for development
  - pytest=7.1 # Only required for development
  - python=3.9
  - pip=22.1
  - requests=2.28
  - scikit-learn=1.1
  - seaborn=0.12
  - spython=0.2
  # Only required for GraphSpace
  - commonmark=0.9
  - docutils=0.18
  - jinja2=3.1
  - mock=4.0
  - recommonmark=0.7
  - sphinx=5.0
  - pip:
     - graphspace_python==1.3.1
     - sphinx-rtd-theme==1.0.0
