name: Build SPRAS Containers

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

jobs:
  build-and-remove-omics1:
    uses: "./.github/workflows/build-and-remove-template.yml"
    with:
      path: docker-wrappers/OmicsIntegrator1
      container: reedcompbio/omics-integrator-1
      tag: latest
  build-and-remove-omics2:
    uses: "./.github/workflows/build-and-remove-template.yml"
    with:
      path: docker-wrappers/OmicsIntegrator2
      container: reedcompbio/omics-integrator-2
      tag: latest
  build-and-remove-pathlinker:
    uses: "./.github/workflows/build-and-remove-template.yml"
    with:
      path: docker-wrappers/PathLinker
      container: reedcompbio/pathlinker
      tag: v2
  build-and-remove-meo:
    uses: "./.github/workflows/build-and-remove-template.yml"
    with:
      path: docker-wrappers/MEO
      container: reedcompbio/meo
      tag: latest
  build-and-remove-mincostflow:
    uses: "./.github/workflows/build-and-remove-template.yml"
    with:
      path: docker-wrappers/MinCostFlow
      container: reedcompbio/mincostflow
      tag: latest
  build-and-remove-allpairs:
    uses: "./.github/workflows/build-and-remove-template.yml"
    with:
      path: docker-wrappers/AllPairs
      container: reedcompbio/allpairs
      tag: v2
  build-and-remove-domino:
    uses: "./.github/workflows/build-and-remove-template.yml"
    with:
      path: docker-wrappers/DOMINO
      container: reedcompbio/domino
      tag: latest
  build-and-remove-cytoscape:
    uses: "./.github/workflows/build-and-remove-template.yml"
    with:
      path: docker-wrappers/Cytoscape
      container: reedcompbio/py4cytoscape
      tag: v3
  build-and-remove-spras:
    uses: "./.github/workflows/build-and-remove-template.yml"
    with:
      path: docker-wrappers/SPRAS
      container: reedcompbio/spras
      tag: v0.2.0
      # Since any change to the SPRAS codebase would constitute a change to
      # the container we produce in this step, build the container regardless
      # of detected changes.
      always_build: true
      context: ./
